This is makeindex, version 2.15 [MiKTeX 2.9.6960 64-bit] (kpathsea + Thai support).
Scanning style file ./Masterproef_NL_2012.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Masterproef_NL_2012.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file Masterproef_NL_2012.acr....done (9 lines written, 0 warnings).
Output written in Masterproef_NL_2012.acr.
Transcript written in Masterproef_NL_2012.alg.
